services:
  # Backend API (FastAPI)
  backend:
    image: ghcr.io/virapa/ajaxsecurflow/backend:latest
    container_name: ajax_proxy_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db
      - redis
    networks:
      - ajaxsecurflow_srv_net
      - ajaxsecurflow_net
    restart: always

  # Celery Worker
  worker:
    image: ghcr.io/virapa/ajaxsecurflow/worker:latest
    container_name: ajax_proxy_worker
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db
      - redis
    command: celery -A backend.app.worker.celery_app worker --loglevel=info -B
    networks:
      - ajaxsecurflow_net
    restart: always

  # Frontend (Next.js)
  frontend:
    image: ghcr.io/virapa/ajaxsecurflow/frontend:latest
    container_name: ajax_proxy_frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - ajaxsecurflow_srv_net
    restart: always

  # Database (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: ajax_proxy_db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ajaxsecurflow_net
    restart: always

  # Cache & Message Broker (Redis)
  redis:
    image: redis:7-alpine
    container_name: ajax_proxy_redis
    volumes:
      - redis_data:/data
    networks:
      - ajaxsecurflow_net
    restart: always

networks:
  ajaxsecurflow_srv_net:
    driver: bridge
  ajaxsecurflow_net:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
